#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Fusee.Forschungsprojekt.Android.Resource", IsApplication=true)]

namespace Fusee.Forschungsprojekt.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Fusee.Base.Imp.Android.Resource.String.ApplicationName = global::Fusee.Forschungsprojekt.Android.Resource.String.ApplicationName;
			global::Fusee.Base.Imp.Android.Resource.String.Hello = global::Fusee.Forschungsprojekt.Android.Resource.String.Hello;
			global::Fusee.Engine.Imp.Graphics.Android.Resource.String.ApplicationName = global::Fusee.Forschungsprojekt.Android.Resource.String.ApplicationName;
			global::Fusee.Engine.Imp.Graphics.Android.Resource.String.Hello = global::Fusee.Forschungsprojekt.Android.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int IPLabel = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int IPinputField = 2131099649;
			
			// aapt resource value: 0x7f06000a
			public const int ToolbarTitle = 2131099658;
			
			// aapt resource value: 0x7f06000e
			public const int action_open_conn_dialog = 2131099662;
			
			// aapt resource value: 0x7f06000d
			public const int canvas_container = 2131099661;
			
			// aapt resource value: 0x7f060002
			public const int connectBtn = 2131099650;
			
			// aapt resource value: 0x7f060009
			public const int disconnectBtn = 2131099657;
			
			// aapt resource value: 0x7f06000c
			public const int minus_btn = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int plus_btn = 2131099659;
			
			// aapt resource value: 0x7f060006
			public const int receivedLabel = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int receivedScrollView = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int receivedTextView = 2131099656;
			
			// aapt resource value: 0x7f060003
			public const int statusLabel = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int statusScrollView = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int statusTextView = 2131099653;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int connection_dialog_layout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int main_activity_layout = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int menu_main = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int actionbar_title = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int unsupported = 2130968580;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
